version: '3'
services:
  webapp:
    image: webapp
    build: ./webapp
    container_name: webapp
    #volumes:
    #- ./webapp/app:/app/ # strictly for development purposes; this statement overrides the /app folder, therefore the developer has to manually run `npm install`
    ports:
    - "80:8080"
